### ISSUE TITLE
Update ruby

### ISSUE THREAD

**Issue by JPS09** [sbriclot/fleet#77]
We should update to 2.6.7 in prod as well as in dev
![image](https://user-images.githubusercontent.com/58084593/113590654-331d7880-9633-11eb-99c1-5584d3f6e676.png)

**Comment by sbriclot** [comment]
Why release 2.6.7 ? 
The latest stable releases are 2.7.3 and 3.0.1, if we decide to upgrade, it's better to directly use the last one.

**Comment by JPS09** [comment]
> Why release 2.6.7 ? 
> The latest stable releases are 2.7.3 and 3.0.1, if we decide to upgrade, it's better to directly use the last one.

These are major releases, the one suggested by heroku is a minor update to the one we're currently using. We might need to also update rails if we go for these ones

**Comment by JPS09** [comment]
I successfully updated ruby to 3.0.3 and webpacker to make it work
